USE AdventureWorks2014
GO
CREATE PROCEDURE dbo.DueDateTodayShar
AS
	SELECT BOOK.Title AS 'Book Title:', BORROWER.Name AS 'Borrower Name:', BORROWER.Address AS 'Borrower Address:'
	FROM BOOK
	INNER JOIN BOOK_LOANS
	ON BOOK.BookIdA = BOOK_LOANS.BookIdC
	INNER JOIN BORROWER
	ON BOOK_LOANS.CardNo = BORROWER.CardNo
	INNER JOIN LIBRARY_BRANCH
	ON BOOK_LOANS.BranchIdA = LIBRARY_BRANCH.BranchIdC
	WHERE BOOK_LOANS.DueDate = '03-08-18' AND LIBRARY_BRANCH.BranchName = 'Sharpstown'
GO

EXEC DueDateTodayShar